// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Account = {
  /**
   * Keep passwords in the OS keyring between runs, for every server; they
   * are never written here.
   */
  rememberPassword: boolean
  /**
   * Log in on startup, to every server with a remembered password. Without
   * one there is nothing to log in with, so this does nothing on its own.
   */
  autoLogin: boolean
}
