// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Account = { username: string, 
/**
 * Keep the password in the OS keyring between runs; it is never written here.
 */
rememberPassword: boolean, 
/**
 * Log in on startup with the remembered password. Without one there is
 * nothing to log in with, so this does nothing on its own.
 */
autoLogin: boolean, };
