// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An AI a room can be given.
 */
export type AiChoice = { 
/**
 * What `ADDBOT` names it: an engine AI's directory, or a Lua AI's `name`.
 */
name: string, 
/**
 * Implemented by the game in Lua rather than shipped by the engine. Such
 * an AI is a game mode -- one per room, and nothing to give a bonus to.
 */
lua: boolean, };
