// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An AI a room can be given.
 */
export type AiChoice = { 
/**
 * What `ADDBOT` names it: an engine AI's directory, or a Lua AI's `name`.
 */
name: string, 
/**
 * The game's one-line description; empty for engine AIs.
 */
desc: string, };
