// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which PvE opponent a room is set up against.
 *
 * The widget reads this from the LuaAI on each team; a lobby reads it from
 * the AI names in the room, which is the same string before the game starts.
 */
export type AiType = "Raptors" | "Scavengers" | "Barbarian";
