// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why an alert was raised, so the front end can honour the setting for it.
 */
export type AlertKind = "privateMessage" | "mention" | "friendOnline" | "gameEnded" | "vote" | "gameStarting" | "ring";
