// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How loudly to say that something happened.
 */
export type Alert = "off" | "lobby" | "desktop";
