// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Arrangement } from "./Arrangement";
import type { Source } from "./Source";

/**
 * The arrangement the game will use, as the anchors it was written with --
 * curvature included, which the drawn polygons above have already spent.
 * What an editor starts from.
 */
export type ArrangementView = { arrangement: Arrangement, source: Source, };
