// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Box } from "./Box";

/**
 * One team-count's worth of boxes. The index in `startboxes` is the ally team.
 */
export type Arrangement = { startboxes: Array<Box>, };
