// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoginFailure } from './LoginFailure'
import type { Settings } from './Settings'

/**
 * How the start's logins went.
 */
export type AutoLogin = {
	/**
	 * The settings as the logins left them: a login writes the account back,
	 * and our own write raises no change event.
	 */
	settings: Settings
	failures: Array<LoginFailure>
}
