// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a room needs, and whether we have it.
 */
export type Availability = { engine: boolean, game: boolean, map: boolean, };
