// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What BAR's launcher config says, for one setup.
 */
export type BarConfig = {
	/**
	 * The lobby server Chobby logs in to.
	 */
	host: string
	port: number
	/**
	 * What BAR calls that server.
	 */
	name: string
	/**
	 * `PRD_RAPID_REPO_MASTER`: where BAR's games are.
	 */
	rapidMaster: string
	/**
	 * `PRD_HTTP_SEARCH_URL`: where BAR's maps are.
	 */
	search: string
}
