// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncView } from "./SyncView";

export type BattleStatusView = { ready: boolean, team: number, allyTeam: number, player: boolean, handicap: number, sync: SyncView, side: number, };
