// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BattleSort } from "./BattleSort";
import type { ModeFilter } from "./ModeFilter";

/**
 * Which rooms the list shows. Chobby words these the other way round, as
 * "Filter out:" checkboxes, where ticking one means seeing less; stated
 * positively, a toggle that is on means that kind of room is in the list.
 */
export type BattleList = { showPassworded: boolean, showLocked: boolean, 
/**
 * Rooms nobody has joined yet.
 */
showEmpty: boolean, 
/**
 * Rooms whose game has already started.
 */
showRunning: boolean, mode: ModeFilter, sort: BattleSort, 
/**
 * Largest or latest first. Ignored by `BattleSort::Relevance`, which has
 * a fixed order of its own.
 */
sortDescending: boolean, };
