// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a room can be ordered by: two orders made of several things, and
 * the columns.
 */
export type BattleSort =
	'relevance' | 'modded' | 'players' | 'title' | 'map' | 'rank'
