// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BotView } from "./BotView";
import type { LayoutView } from "./LayoutView";
import type { StartRectView } from "./StartRectView";

export type BattleView = { id: number, founder: string, ip: string, port: number, maxPlayers: number, passworded: boolean, locked: boolean, mapHash: string, mapName: string, engineName: string, engineVersion: string, title: string, gameName: string, 
/**
 * Sorted; includes the host bot and spectators.
 */
members: Array<string>, spectatorCount: number, playerCount: number, layout: LayoutView | null, bots: Array<BotView>, startRects: Array<StartRectView>, };
