// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A room, and the server it is on.
 */
export type BattleOn = { server: string; id: number }
