// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModeFilter } from './ModeFilter'
import type { SortStep } from './SortStep'

/**
 * Which rooms the list shows. Chobby words these the other way round, as
 * "Filter out:" checkboxes, where ticking one means seeing less; stated
 * positively, a toggle that is on means that kind of room is in the list.
 */
export type BattleList = {
	showPassworded: boolean
	showLocked: boolean
	/**
	 * Rooms nobody has joined yet.
	 */
	showEmpty: boolean
	/**
	 * Rooms whose game has already started.
	 */
	showRunning: boolean
	/**
	 * Narrow the list to rooms with a friend in them. Off by default: it
	 * empties the list for anyone who has not added anybody.
	 */
	friendsOnly: boolean
	mode: ModeFilter
	/**
	 * How the rooms are ordered: every factor there is, the first deciding
	 * and each later one breaking the ties left by those before it. The list
	 * page drags them into order and flips each one's direction. A file that
	 * names some of them, or a sort from before there were steps, is
	 * completed from the default order.
	 */
	sort: Array<SortStep>
}
