// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Preset } from "./Preset";

/**
 * The file we keep, with a version so a future shape can be told from this one.
 */
export type Book = { version: number, presets: Array<Preset>, };
