// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Settings } from './Settings'
import type { VersionView } from './VersionView'

/**
 * What the page would otherwise open by asking for, one call behind another
 * while the first screen is drawn without the answers. Handed over with the
 * page instead, as a script that runs ahead of the page's own.
 */
export type Boot = {
	settings: Settings
	/**
	 * What was done at this start about a settings file that did not parse.
	 */
	recovered: string | null
	/**
	 * The version the start is installing ahead of the app, if one was kept.
	 */
	keptUpdate: string | null
	version: VersionView
}
