// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BattleStatusView } from "./BattleStatusView";

export type BotView = { name: string, owner: string, status: BattleStatusView, teamColour: number, ai: string, 
/**
 * What the AI has been told about itself, where a room can tell it
 * anything. A room on the server keeps this nowhere, so it is empty
 * there rather than absent.
 */
options: { [key in string]: string }, };
