// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BattleStatusView } from "./BattleStatusView";

export type BotView = { name: string, owner: string, status: BattleStatusView, teamColour: number, ai: string, };
