// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from "./Point";

/**
 * One team's box.
 */
export type Box = { 
/**
 * Two points are opposite corners of a rectangle; three or more are a
 * polygon in order.
 */
poly: Array<Point>, };
