// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The boxes to draw, already flattened into polygons in the 0-200 space the
 * minimap uses.
 */
export type BoxesView = { 
/**
 * One polygon per ally team, in ally-team order.
 */
polys: Array<Array<[number, number]>>, 
/**
 * `override` when somebody chose these for this room, `set` when they are
 * the map's own for this many teams.
 */
source: string, 
/**
 * The team count they were resolved for.
 */
teams: number, 
/**
 * Whether the map offers arrangements for other team counts too, which is
 * what makes a "boxes for N teams" choice meaningful.
 */
available: Array<number>, };
