// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A server every install has: its card stays on the list.
 */
export type Builtin = 'bar' | 'recoil'
