// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of the server's channel directory.
 */
export type ChannelSummaryView = { name: string, members: number, };
