// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Chat = {
  /**
   * Whether to drop the host's machine-readable lines rather than show them.
   *
   * SPADS rides structured state on battle chat as `BarManager|{…}`, which
   * this already parses into the room. Chobby hides the same lines behind
   * the same default, calling it "filter bot chatter"
   * (`gui_settings_window.lua:1146`).
   */
  filterHostChatter: boolean
  /**
   * Lines kept per room before the oldest are dropped.
   */
  maxLines: number
  /**
   * Rooms left out of the unread count on the Chat tab, by name: a
   * channel's name, or `@name` for a person — on every server that has
   * one. A line that names you still counts.
   */
  muted: Array<string>
}
