// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatKind } from "./ChatKind";

export type ChatLine = { seq: number, from: string, text: string, kind: ChatKind, };
