// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Chat = { 
/**
 * Lines kept per room before the oldest are dropped.
 */
maxLines: number, };
