// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatKind } from "./ChatKind";

export type ChatLine = { seq: number, 
/**
 * Where this was said. `#battle` is the room we are in, `@name` is a
 * private conversation, and anything else is a channel — which cannot
 * collide, because teiserver only accepts `\w+` as a channel name.
 */
room: string, from: string, text: string, kind: ChatKind, };
