// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Chat = { 
/**
 * Whether to drop the host's machine-readable lines rather than show them.
 *
 * SPADS rides structured state on battle chat as `BarManager|{…}`, which
 * this already parses into the room. Chobby hides the same lines behind
 * the same default, calling it "filter bot chatter"
 * (`gui_settings_window.lua:1146`).
 */
filterHostChatter: boolean, 
/**
 * Lines kept per room before the oldest are dropped.
 */
maxLines: number, 
/**
 * Channels to rejoin at login. The server forgets you were in them the
 * moment you disconnect, so remembering is the client's job — and keeping
 * it here means you can also just write one in.
 */
channels: Array<string>, };
