// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One part of the room's content here held to the hash the room announced
 * for it: the engine's checksum of the archive and what it uses.
 */
export type CheckView =
	| { verdict: 'checking' }
	| { verdict: 'same'; hash: number }
	| { verdict: 'differs'; ours: number; room: number }
	| { verdict: 'unchecked'; why: string }
