// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Problem } from "./Problem";
import type { Symbol } from "./Symbol";

export type Check = { problems: Array<Problem>, outline: Array<Symbol>, };
