// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A commit on GitHub, as the Mods pane asks after one.
 */
export type CommitView = {
	sha: string
	/**
	 * When it was committed, as GitHub says.
	 */
	date: string | null
}
