// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Holding on to the server, and letting it go.
 */
export type Connection = { 
/**
 * Minutes without a key pressed or a click in the window before the
 * connection is dropped and not retried; `0` keeps it however long.
 *
 * A dropped connection otherwise comes back on its own, which is right
 * for a window in use and wrong for one that was forgotten: it holds a
 * seat in a room for nobody, and keeps the account logged in from a
 * machine its owner may have left. A running game never counts as idle,
 * whatever the lobby window sees. The window stays open, one click from
 * logging in again.
 */
idleDisconnectMinutes: number, };
