// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What of a room's engine, game and map this machine already has.
 */
export type ContentView = { engine: boolean, game: boolean, map: boolean, };
