// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckView } from './CheckView'
import type { MutatorView } from './MutatorView'

/**
 * The room's game and map here held to its hashes. `None` for a part that
 * is not here, or that the room announced no hash for.
 */
export type ContentCheckView = {
	game: CheckView | null
	map: CheckView | null
	/**
	 * What the room loads on top of its game, in load order; empty for a
	 * room that loads nothing.
	 */
	mutators: Array<MutatorView>
}
