// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BattleStatusView } from "./BattleStatusView";
import type { BattleView } from "./BattleView";
import type { BotView } from "./BotView";
import type { ChatLine } from "./ChatLine";
import type { EngineStatus } from "./EngineStatus";
import type { GameRunningView } from "./GameRunningView";
import type { LayoutView } from "./LayoutView";
import type { MyBattleView } from "./MyBattleView";
import type { NoticeLevel } from "./NoticeLevel";
import type { OptionChangeView } from "./OptionChangeView";
import type { Phase } from "./Phase";
import type { StartRectView } from "./StartRectView";
import type { UserStatusView } from "./UserStatusView";
import type { UserView } from "./UserView";
import type { VoteView } from "./VoteView";

/**
 * One change to apply to the mirrored state.
 */
export type Delta = { "type": "phase", "data": Phase | null } | { "type": "userAdded", "data": UserView } | { "type": "userRemoved", "data": { name: string, } } | { "type": "userStatus", "data": { name: string, status: UserStatusView, } } | { "type": "battleOpened", "data": BattleView } | { "type": "battleClosed", "data": { id: number, } } | { "type": "battleInfo", "data": { id: number, spectatorCount: number, locked: boolean, mapHash: string, mapName: string, } } | { "type": "battleTitle", "data": { id: number, title: string, } } | { "type": "battleLayout", "data": { id: number, layout: LayoutView, } } | { "type": "member", "data": { id: number, name: string, joined: boolean, } } | { "type": "memberStatus", "data": { name: string, status: BattleStatusView, teamColour: number, } } | { "type": "bot", "data": { id: number, name: string, bot: BotView | null, } } | { "type": "startRect", "data": { allyTeam: number, rect: StartRectView | null, } } | { "type": "scriptTags", "data": { set: Array<[string, string]>, removed: Array<string>, } } | { "type": "modOption", "data": { key: string, value: string, change: OptionChangeView | null, } } | { "type": "vote", "data": VoteView | null } | { "type": "myBattle", "data": MyBattleView | null } | { "type": "gameRunning", "data": GameRunningView | null } | { "type": "engine", "data": EngineStatus } | { "type": "chat", "data": ChatLine } | { "type": "notice", "data": { level: NoticeLevel, text: string, } };
