// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something worth telling the user about a decoded payload.
 */
export type Diagnostic = { "type": "underscoreCorruption", count: number, };
