// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hunk } from "./Hunk";

export type DiffView = { hunks: Array<Hunk>, 
/**
 * The same change as a patch, for copying out.
 */
unified: string, added: number, removed: number, };
