// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A pr-downloader run, and how far along it is.
 */
export type DownloadStatus = { "state": "idle" } | { "state": "running", 
/**
 * What was asked for, for the label.
 */
what: string, current: number, total: number, } | { "state": "failed", what: string, reason: string, } | { "state": "done", what: string, };
