// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An arrangement as the wire carries it, with how long it was allowed to be.
 */
export type Encoded = { value: string, limit: number, };
