// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Both encrypted ways fall back to the other when the server does not greet.
 */
export type Encryption = "stls" | "tls" | "none";
