// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far along the one download this module does is.
 */
export type EngineProgress = { "phase": "finding" } | { "phase": "downloading", got: number, total: number, } | { "phase": "extracting" } | { "phase": "done", version: string, } | { "phase": "failed", reason: string, };
