// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EngineStatus = { "state": "idle" } | { "state": "running", 
/**
 * The engine's process id, when it still has one.
 *
 * `Option` because a reaped child has none, and because it is only
 * ever a hint: what it is for is finding the game's window, which may
 * not exist yet while the engine is loading.
 */
pid: number | null, } | { "state": "exited", code: number | null, };
