// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a fork is one publisher's widget or the players nobody could trace.
 */
export type ForkKind = 'lineage' | 'other'
