// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForkKind } from "./ForkKind";
import type { Install } from "./Install";
import type { WindowStats } from "./WindowStats";

/**
 * One version of a widget name: a publisher's lineage, or "other versions".
 *
 * A lineage is strict on purpose — only ever one publisher — because it is
 * what a future "keep updated" follows. Somebody's modified copy of a widget
 * is a fork of it, never an update to it.
 */
export type Fork = { 
/**
 * `github:<owner>/<repo>:<name>`, `gist:<id>:<name>`,
 * `discord:<poster>:<name>`, `hub:<id>`, or `other`.
 */
key: string, kind: ForkKind, 
/**
 * The lineage the row itself speaks for.
 */
main: boolean, id: string, author: string, description: string, install: Install, image: string, 
/**
 * Every picture, best first; `image` is the first. See `WidgetUsage::images`.
 */
images: Array<string>, 
/**
 * When this version's first and newest revisions were published, as
 * `YYYY-MM-DDTHH:MM:SSZ`; empty when no source said.
 */
first_published: string, last_updated: string, windows: { [key in string]: { [key in string]: WindowStats } }, };
