// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who we are friends with, and who is waiting on an answer.
 */
export type FriendsView = { friends: Array<string>, requests: Array<string>, 
/**
 * Who the server no longer relays anything from.
 */
ignored: Array<string>, };
