// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameSource } from './GameSource'

/**
 * One game, by its exact name, and where it comes from.
 */
export type GameOverride = {
	/**
	 * The game's name exactly as rooms report it, e.g.
	 * `SplinterFaction 0.1.86`. Nothing else matches: not the next version,
	 * not a different case.
	 */
	name: string
	source: GameSource
}
