// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameOverride } from './GameOverride'

/**
 * Games from anywhere but the rooms' own rapid servers.
 */
export type Games = {
	/**
	 * Where exactly one game is to be had, above every list and above the
	 * room's own rapid: a room naming `name` gets it from `source` and from
	 * nowhere else.
	 */
	overrides: Array<GameOverride>
}
