// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The room's game is running; the script password stays in the runtime.
 */
export type GameRunningView = { id: number, ip: string, port: number, };
