// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The room's game is running; the script password stays in the runtime.
 */
export type GameRunningView = {
	id: number
	ip: string
	port: number
	/**
	 * Whether SPADS already has us in this game: we were in the room when it
	 * started, or have connected to it since (`midGameSpecLevel` adds anyone
	 * who does as a spectator). Until then `!joinas` can still put us in on
	 * someone's ID; after, SPADS refuses it as `already been added`.
	 */
	added: boolean
	/**
	 * Whom we play alongside once `!joinas` has put us in on their ID: empty
	 * until the host has said who is on it, `None` while we only watch.
	 */
	playingWith: Array<string> | null
}
