// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One way to fetch a game, in coilbox's hub format
 * (`{kind, value, asset?, filename?}`), so a list, the hub and an override
 * all say it the same way.
 */
export type GameSource =
	| { kind: 'rapid'; value: string }
	| { kind: 'url'; value: string; filename?: string | null }
	| { kind: 'github'; value: string; asset?: string | null }
	| { kind: 'git'; value: string; placeholder?: string | null }
