// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Gauge = { 
/**
 * Bytes of the Lua as edited.
 */
raw: number, 
/**
 * Bytes after minification.
 */
minified: number, 
/**
 * Characters of the base64url payload.
 */
blob: number, 
/**
 * Characters of the whole chat command — what the cap applies to.
 */
command: number, cap: number, fits: boolean, };
