// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeOp } from "./ChangeOp";

export type Hunk = { op: ChangeOp, oldLine: number | null, newLine: number | null, text: string, };
