// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Book } from "./Book";

export type Imported = { book: Book, 
/**
 * Presets in their file whose name we already had, and so left alone.
 */
skipped: number, };
