// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a widget's bytes live.
 */
export type InstallKind = "hub" | "github" | "gist" | "discord" | "none";
