// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file of a widget, and how to check it arrived intact.
 */
export type InstallFile = {
	/**
	 * Path as published, which may carry the directories it sat under
	 * upstream. [`Self::install_path`] is where it goes.
	 */
	path: string
	/**
	 * Base64 MD5 — `VFS.CalculateHash(data, 0)`, the game's own value.
	 */
	content_hash: string
	/**
	 * Empty for a hub archive member, which is not separately addressable,
	 * and for anything the licence withheld.
	 */
	url: string
	/**
	 * Where it goes, relative to `LuaUI/Widgets/`, as the pipeline worked out
	 * from what the widget's own code loads. Empty in an older document.
	 */
	install_path: string
}
