// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What sitting down in a room you just joined should mean.
 *
 * Chobby's three, under the same names it gives them
 * (`gui_settings_window.lua:906`): remember what you did last time, or always
 * one or the other.
 */
export type JoinAs = "remember" | "spectator" | "player";
