// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the two tweak shapes a payload is.
 */
export type Kind = "defs" | "units";
