// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which shape a payload is: one of the two tweak kinds, or the start-box
 * override.
 */
export type Kind = "defs" | "units" | "boxes";
