// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Games with people on the local network, with no server between you.
 */
export type Lan = {
	/**
	 * Whether the lobby listens for rooms on the network, and offers to
	 * announce one of yours.
	 *
	 * Off. Everything else the lobby does it does to a server you chose;
	 * this listens on a multicast group and a broadcast address, and hosting
	 * tells the whole network your name and what you are playing. That is
	 * worth asking for rather than assuming, on a laptop that may be on a
	 * network you do not own. Nothing about it starts until this is on.
	 */
	enabled: boolean
}
