// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentView } from "./ContentView";

/**
 * A game somebody on this network is hosting, as the window draws it.
 *
 * Everything in it came off the wire from an unauthenticated stranger — see
 * `lobby_core::lan` — except [`content`](Self::content), which is this
 * machine's own answer about whether it could play the thing being offered.
 * That pairing is the point of the type: the description is theirs, the
 * judgement is ours, and a row says both.
 */
export type LanGameView = { 
/**
 * The announcement's own id, which is what a join names. New each time a
 * room is opened, so it cannot mean a different game than the one clicked.
 */
id: string, title: string, host: string, 
/**
 * Where it is, for somebody deciding whether they recognise the machine.
 * The address the announcement came *from*, never one its sender chose.
 */
address: string, engine: string, game: string, map: string, 
/**
 * The names the host has written into the start script. Joining under one
 * of these is the only way the engine's server will let anybody in, so
 * this is also the list of people who can come.
 */
seats: Array<string>, 
/**
 * Already started, and so too late to join. Listed anyway: "you are late"
 * is worth more than a row that vanishes as you reach for it.
 */
running: boolean, 
/**
 * Whether this machine has what it would take to play.
 */
content: ContentView, };
