// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The room this machine hosts, for the page that shows it.
 */
export type LanHostView = {
	/**
	 * As announced on the network, which is how the battle list keys it.
	 */
	id: number
	port: number
	title: string
	/**
	 * Who is waiting for `!accept`.
	 */
	pending: Array<string>
}
