// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A room found on the network, for the battle list.
 */
export type LanRoomView = {
	id: number
	address: string
	port: number
	title: string
	host: string
	engineVersion: string
	game: string
	map: string
	players: number
	maxPlayers: number
	passworded: boolean
}
