// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanGameView } from "./LanGameView";

/**
 * What is on this network.
 *
 * Empty and `listening: false` is the ordinary state of a machine with no
 * LAN game anywhere near it, which is most of them — so the front end draws
 * nothing at all rather than an empty section, and there is no setting to
 * turn off something that is already nothing.
 */
export type LanView = { games: Array<LanGameView>, 
/**
 * Who else has modlobby open here and no game of their own, so a host
 * picks a guest's name off a list rather than spelling it — a name spelled
 * wrong is a guest the engine will not let in.
 */
people: Array<string>, 
/**
 * Whether modlobby has a socket to hear any of this on. False where the
 * port was taken or the network refused it, which is worth saying: an
 * empty list means two different things and only one of them is "nobody
 * is playing".
 */
listening: boolean, };
