// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A server the start could not log in to, and why.
 */
export type LoginFailure = { server: string; message: string }
