// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the map list says about a map, out of the same published feed.
 */
export type MapFacts = {
	/**
	 * The name as its author writes it, where that differs from the spring
	 * name a start script has to use.
	 */
	displayName: string
	author: string
	/**
	 * In map units of 512 elmos a side, as every BAR lobby says it: `16 x
	 * 16` is the usual medium.
	 */
	width: number
	height: number
	playersMin: number
	playersMax: number
	/**
	 * One of the maps BAR vouches for, which is what its own rooms play.
	 */
	certified: boolean
	/**
	 * `ice`, `desert`, `metal` — as the feed spells them.
	 */
	terrain: Array<string>
	tags: Array<string>
}
