// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The two things a lobby needs from the index.
 */
export type MapIndex = { 
/**
 * Spring name, exactly as `BATTLEOPENED` reports it, to the published
 * preview URL.
 */
images: { [key in string]: string }, 
/**
 * Archive file name without its extension (`acidicquarry_5.17`) to the
 * spring name (`AcidicQuarry 5.17`), which nothing on disk records.
 */
names: { [key in string]: string }, };
