// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MapFacts } from './MapFacts'

/**
 * The two things a lobby needs from the index.
 */
export type MapIndex = {
	/**
	 * Spring name, exactly as `BATTLEOPENED` reports it, to the published
	 * preview URL.
	 */
	images: { [key in string]: string }
	/**
	 * Archive file name without its extension (`acidicquarry_5.17`) to the
	 * spring name (`AcidicQuarry 5.17`), which nothing on disk records.
	 */
	names: { [key in string]: string }
	/**
	 * By spring name: what a list of maps shows besides the picture.
	 */
	maps: { [key in string]: MapFacts }
}
