// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Player-versus-what. Read off the room title, which is all the list has:
 * the server only sends a room's AI once you are in it.
 */
export type ModeFilter = "all" | "pve" | "pvp";
