// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckView } from './CheckView'

/**
 * A mutator the room loads: whether it is here, and, where its host
 * announced a checksum, this copy held to it. The engine checks a mutator
 * against nothing, so this is the only thing that does.
 */
export type MutatorView = {
	name: string
	here: boolean
	check: CheckView | null
}
