// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckView } from './CheckView'

/**
 * A mutator the room loads: whether it is here, and, where its host
 * announced a checksum, this copy held to it. The engine checks a mutator
 * against nothing, so this is the only thing that does.
 */
export type MutatorView = {
	/**
	 * What the room loads it by: the name inside it, or for one built from
	 * a commit, the build's file name.
	 */
	name: string
	/**
	 * What to call it: the name inside it where this copy is here to read.
	 */
	title: string
	here: boolean
	check: CheckView | null
	/**
	 * `github:owner/repo@<commit>` for one built from a commit.
	 */
	source: string | null
	/**
	 * When that commit was made, as the host announced it.
	 */
	date: string | null
}
