// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptionChangeView } from "./OptionChangeView";
import type { VoteView } from "./VoteView";

export type MyBattleView = { 
/**
 * Who SPADS says is bossing the room, when it has said.
 */
boss: string | null, id: number, gameHash: string, 
/**
 * Lowercase script-tag keys (`game/modoptions/tweakdefs`, `game/hosttype`, …).
 */
scriptTags: { [key in string]: string }, vote: VoteView | null, 
/**
 * Modoption changes seen this session, oldest first.
 */
history: Array<OptionChangeView>, };
