// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptionChangeView } from './OptionChangeView'
import type { SeatOnItsWayView } from './SeatOnItsWayView'
import type { VoteView } from './VoteView'

export type MyBattleView = {
	/**
	 * Who SPADS says is bossing the room, when it has said.
	 */
	boss: string | null
	/**
	 * How the room balances itself: `off`, `on`, `advanced`. `null` where the
	 * room has not said, which is not the same as `off`: a host without BAR's
	 * BarManager plugin never reports it.
	 */
	autoBalance: string | null
	/**
	 * The SPADS preset the room runs under (`team`, `ffa`, `coop`, `duel`,
	 * `tourney`, `custom`), `null` where the room has not said.
	 */
	preset: string | null
	id: number
	gameHash: string
	/**
	 * Lowercase script-tag keys (`game/modoptions/tweakdefs`, `game/hosttype`, …).
	 */
	scriptTags: { [key in string]: string }
	vote: VoteView | null
	/**
	 * Modoption changes seen this session, oldest first.
	 */
	history: Array<OptionChangeView>
	/**
	 * A ready given in advance, armed until the server's next automatic
	 * unready -- being seated from the queue, or a game ending -- which it
	 * answers once. Never remembered past this room.
	 */
	preReady: boolean
	/**
	 * The ready our newest request asks for, while the server still shows
	 * otherwise. Drawn at once as on its way; the server's word is still
	 * what is true.
	 */
	readyOnItsWay: boolean | null
	/**
	 * The seat our newest request asks for, likewise.
	 */
	seatOnItsWay: SeatOnItsWayView | null
	/**
	 * When the status we last asked for leaves, in Unix milliseconds, while
	 * the flood window holds it: the room takes five changes in eight
	 * seconds. Drawn as a hairline draining along the pending segment.
	 */
	heldUntilMs: number | null
}
