// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MyBattleView = { id: number, gameHash: string, 
/**
 * Lowercase script-tag keys (`game/modoptions/tweakdefs`, `game/hosttype`, …).
 */
scriptTags: { [key in string]: string }, };
