// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One story.
 */
export type NewsItem = { 
/**
 * The permalink, which is what `<guid>` holds. Identifies the item
 * everywhere: in the read marks, and as the key its picture is asked for
 * by. It does not change when the story is edited, which is the whole
 * reason an edit never counts as something new.
 */
id: string, title: string, summary: string, link: string, 
/**
 * Unix seconds from `<pubDate>`; `None` when it could not be read.
 */
publishedAt: number | null, 
/**
 * The banner, if the item published one. Fetched through the app rather
 * than by the webview, which cannot reach the CDN it lives on.
 */
image: string | null, };
