// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NewsItem } from "./NewsItem";

/**
 * The list, and how much of it is new since it was last looked at.
 *
 * One answer rather than two commands, so the count on the tab and the page
 * behind it can never disagree about what was in the feed.
 */
export type NewsFeed = { items: Array<NewsItem>, unread: number, };
