// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What is worth interrupting someone for.
 *
 * Only raised while the window is not focused: a toast for something already
 * on screen is noise. Chobby draws the same line, alerting only when its
 * window is in the background.
 */
export type Notifications = { enabled: boolean, 
/**
 * Someone messaged you directly.
 */
privateMessage: boolean, 
/**
 * Someone said your name in a channel or in your room.
 */
mention: boolean, 
/**
 * A vote opened in your room.
 */
vote: boolean, 
/**
 * Your room's game started.
 */
gameStarting: boolean, 
/**
 * Someone rang you.
 */
ring: boolean, };
