// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Alert } from "./Alert";

/**
 * What is worth saying something about, and where.
 */
export type Notifications = { 
/**
 * Someone messaged you directly.
 */
privateMessage: Alert, 
/**
 * Someone said your name in a channel or in your room.
 */
mention: Alert, 
/**
 * Someone rang you.
 */
ring: Alert, 
/**
 * A friend logged in.
 */
friendOnline: Alert, 
/**
 * A vote opened in your room.
 */
vote: Alert, 
/**
 * Your room's game started.
 */
gameStarting: Alert, 
/**
 * Your room's game finished.
 */
gameEnded: Alert, };
