// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A default, in the one of three shapes Lua wrote it in.
 */
export type OptionValue = boolean | number | string;
