// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A modoption that changed while we watched — one side of a diff.
 */
export type OptionChangeView = { seq: number, key: string, from: string, to: string, by: string | null, };
