// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a lobby is meant to render for one entry.
 *
 * `Section` declares a tab; `Subheader` and `Separator` are layout marks
 * inside one. Anything BAR adds later arrives as `Other` rather than failing
 * the parse, so a new control type costs us a plain row, not a broken app.
 */
export type OptionType = "bool" | "number" | "string" | "list" | "section" | "subheader" | "separator" | "link" | { "other": string };
