// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The lobby raised over a running game by a hotkey.
 */
export type Overlay = { enabled: boolean, 
/**
 * A Tauri accelerator, e.g. `Alt+Shift+L`.
 *
 * A global hotkey beats the focused window, so a collision does not
 * merely conflict — it silently eats a game action for as long as a game
 * is running. The default was checked against BAR's shipped binds: `sc_l`
 * is taken plain and with Shift (cycling fire state), and the whole game
 * binds only two Alt+Shift combinations, neither of them this one.
 */
hotkey: string, 
/**
 * Whether hiding the overlay should put the game back in front.
 */
returnFocusToGame: boolean, };
