// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A multi-line battle-room paste, and how far it has got. Worth a banner
 * rather than a toast: paced under SPADS's counters a paste can take a
 * minute, and a pane that sits still for a minute reads as nothing
 * happening.
 *
 * Progress is what the host has answered, not what left the socket: as boss
 * the whole paste is gone in seconds while SPADS is still chewing through
 * the tweak blobs. It is measured in bytes rather than lines, since a
 * 16 KB tweak costs the host far more than a `!bSet a 1`, and a bar that
 * stepped the same for both stalled on the blobs. No time estimate: the
 * host's pace is not ours to know, and a wrong number is worse than none.
 */
export type PasteStatus = { "state": "idle" } | { "state": "running", 
/**
 * Lines handed to the scheduler, after skipping.
 */
total: number, 
/**
 * Lines that have left the socket.
 */
sent: number, 
/**
 * Lines the host will answer: the `!` and `$` commands among `total`.
 */
commands: number, 
/**
 * Commands the host has answered so far.
 */
applied: number, 
/**
 * Settings dropped because the room already had them.
 */
skipped: number, 
/**
 * Bytes across all the commands.
 */
work: number, 
/**
 * Bytes across the commands answered so far.
 */
done: number, } | { "state": "done", total: number, commands: number, applied: number, skipped: number, 
/**
 * Stopped by the reader; what had not left was dropped.
 */
cancelled: boolean, };
