// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Paths = { 
/**
 * The BAR data directory modlobby writes (`engine/`, `games/`, `maps/`);
 * its own when unset. The launcher's and bar-lobby's installs are read
 * either way, so their content is never fetched twice.
 */
dataDir: string | null, };
