// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Paths = { 
/**
 * The BAR data directory (`engine/`, `games/`, `maps/`); the launcher's when unset.
 */
dataDir: string | null, };
