// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlannedBox } from "./PlannedBox";

/**
 * What applying a preset would do.
 */
export type Plan = { 
/**
 * Chat lines, in order. Every one is a SPADS command.
 */
lines: Array<string>, 
/**
 * Ally teams whose start box the preset names, and the box. For showing
 * what is about to happen; the wire form is one of the `lines`.
 */
startBoxes: Array<PlannedBox>, 
/**
 * Set when the preset has boxes that could not be turned into a line.
 */
startBoxesUnsent: boolean, 
/**
 * Settings the room already has, which is why they are not in `lines`.
 */
alreadySet: number, };
