// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Playing rather than watching.
 */
export type Play = { 
/**
 * Whether a seat may be taken in a public room.
 *
 * Off by default, and deliberately so: in a public room a slot belongs to
 * a real player waiting for a game, and a client that takes one to try
 * something out has spoiled someone's evening. Turn it on when you mean
 * to play; a room of your own (`!privatehost`) never needs it.
 */
inPublicRooms: boolean, };
