// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The player's files — engine settings, hotkeys, widget state — as the
 * Settings page shows them: where they can be copied from, and the copies
 * taken before each launch.
 */
export type PlayerFilesView = { 
/**
 * The data directory the engine writes, where the files live.
 */
write: string, 
/**
 * Other installs on this machine whose settings are worth copying.
 */
sources: Array<string>, 
/**
 * Snapshot directories, newest first; each is named for when it was
 * taken, in UTC.
 */
snapshots: Array<string>, };
