// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A point, in the same 0-200 space as `ADDSTARTRECT`.
 *
 * `y` is the map's Z axis; the game reads these as `p.x, p.y` and scales both
 * by `mapSize / 200`.
 */
export type Point = { x: number, y: number, 
/**
 * Spline weight, when the box is a curve rather than straight edges.
 */
strength: number | null, };
