// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StartBox } from "./StartBox";

/**
 * One saved setup.
 */
export type Preset = { name: string, 
/**
 * The map's full name, as the battle list spells it.
 */
map: string | null, 
/**
 * `!bSet` keys and their values, as strings because that is what goes on
 * the wire. A number or a boolean in someone else's file is normalised on
 * the way in and put back on the way out — see [`crate::chobby`].
 */
modoptions: { [key in string]: string }, 
/**
 * SPADS room settings: preset, teamSize, nbTeams, autoBalance,
 * balanceMode, locked.
 */
battle: { [key in string]: string }, 
/**
 * Ally team number to its box. Kept sparse: a preset can name team 2
 * without naming team 1, and Chobby's own file does.
 */
startBoxes: { [key in number]: StartBox }, 
/**
 * AI slots, carried through exactly as they were written.
 *
 * Opaque on purpose. Their shape is whatever Chobby's `AddAi` accepted at
 * the time — library, version, ally number, colour, handicap, and a bag of
 * AI options — and re-encoding a structure we do not fully model is how
 * you lose somebody's carefully tuned bot setup. Round-tripped verbatim
 * until there is a reason to read it.
 */
bots: Record<string, unknown>, created: number, updated: number, 
/**
 * `None` until it has been applied to a room once.
 */
lastUsed: number | null, };
