// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One place the Lua stops making sense. Lines and columns are 1-based, and
 * the end is exclusive, which is how an editor draws a marker.
 */
export type Problem = { line: number, column: number, endLine: number, endColumn: number, message: string, };
