// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A game a server's own rapid publishes, and the tag that fetches it.
 */
export type Published = { tag: string; name: string }
