// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a master index turned out to list, for whoever typed its address.
 */
export type RapidSummary = {
  /**
   * Repos the server hosts itself.
   */
  own: number
  /**
   * Repos of BAR's it lists beside them.
   */
  bars: number
}
