// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a delete actually took out.
 */
export type Removed = {
  /**
   * Whether the widget was listed in `order`.
   */
  order_entry: boolean
  /**
   * Whether it had saved settings in `data`.
   */
  settings: boolean
}
