// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A replay as the front end lists it.
 */
export type ReplayView = { path: string, playedAt: string, map: string, engine: string, bytes: number, };
