// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A replay as the front end lists it.
 */
export type ReplayView = {
	path: string
	playedAt: string
	map: string
	engine: string
	bytes: number
	/**
	 * Seconds of game time, which stops for pauses and counts the whole game
	 * even for someone who joined late. `null` for a game left before it ended.
	 */
	gameSeconds: number | null
	/**
	 * Seconds on the clock, from the game starting to it ending.
	 */
	wallSeconds: number | null
}
