// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The posture a request of ours asks for: a seat on an ally team, or none.
 */
export type SeatOnItsWayView = {
	player: boolean
	/**
	 * Meaningful for a player; zero for a spectator.
	 */
	allyTeam: number
}
