// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which teiserver to talk to.
 */
export type Server = { host: string, port: number, 
/**
 * teiserver speaks TLS on 8201 and plain TCP on 8200.
 */
tls: boolean, };
