// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Encryption } from "./Encryption";

/**
 * Which teiserver to talk to.
 *
 * These keys replaced `port` and `tls`, so a file that still carries those
 * is read as the defaults below.
 */
export type Server = { host: string, 
/**
 * How the connection is encrypted, and what it falls back to.
 */
encryption: Encryption, 
/**
 * Where `STLS` upgrades to TLS, and where `none` stays unencrypted.
 */
plainPort: number, 
/**
 * Where TLS starts from the first byte.
 */
tlsPort: number, };
