// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BattleView } from "./BattleView";
import type { ChannelView } from "./ChannelView";
import type { FriendsView } from "./FriendsView";
import type { GameRunningView } from "./GameRunningView";
import type { MyBattleView } from "./MyBattleView";
import type { Phase } from "./Phase";
import type { UserView } from "./UserView";

/**
 * One server's session.
 */
export type ServerSnapshot = { 
/**
 * Which server: its host, lowercased.
 */
server: string, phase: Phase | null, 
/**
 * Seconds until the runtime tries the last credentials again on its
 * own, while it means to; `None` when it does not — connected, logged
 * out, or never logged in. A count, not a moment: the runtime's clock
 * is not the window's.
 */
retryIn: number | null, me: string | null, users: Array<UserView>, battles: Array<BattleView>, myBattle: MyBattleView | null, gameRunning: GameRunningView | null, 
/**
 * Channels we are in. Chat lines are not replayed — a reload keeps
 * whichever backlog the front end still holds — but membership is, so the
 * channel list is right the moment the window comes back.
 */
channels: Array<ChannelView>, friends: FriendsView, };
