// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Builtin } from './Builtin'

/**
 * A lobby server, and the account on it.
 */
export type ServerEntry = {
	/**
	 * Which of the servers every install has this is, if it is one.
	 */
	builtin: Builtin | null
	/**
	 * Where it is. The server is known by this, trimmed and lowercased, so
	 * changing it makes a different server: a new account, a new password.
	 */
	host: string
	/**
	 * What the app calls it; the host when empty.
	 */
	name: string
	/**
	 * Ports to try, each both encrypted ways (`STLS` and TLS) at once; the
	 * way that answers first is remembered and tried first next time.
	 */
	ports: Array<number>
	/**
	 * Whether an unencrypted connection will do once every encrypted way has
	 * failed. Off unless the server has nothing else: the password and every
	 * message would cross the network readable.
	 */
	allowUnencrypted: boolean
	/**
	 * Where the server's web pages are — a forgotten password is reset
	 * there — when that is not `https://<host>`.
	 */
	website: string | null
	/**
	 * The server's own rapid master index (`https://…/repos.gz`), where the
	 * games its rooms run are published. Without one its games are looked
	 * for in BAR's, which is right for a server running stock BAR. A game is
	 * only ever looked for in its own server's index: a mod's name is never
	 * sent to BAR's servers, nor to any other server's.
	 */
	rapid: string | null
	/**
	 * The server's own map search (`https://…/find`, the springfiles API
	 * pr-downloader speaks), for maps of its own. Asked only for a map that
	 * is not one of BAR's; BAR's search is asked only for those that are.
	 */
	maps: string | null
	/**
	 * The account on this server.
	 */
	username: string
	/**
	 * Channels to rejoin at login. The server forgets you were in them the
	 * moment you disconnect, so remembering is the client's job — and keeping
	 * it here means you can also just write one in.
	 */
	channels: Array<string>
	/**
	 * Whether this server is logged in to at startup; `null` follows
	 * `account.autoLogin`. A value that matches that one follows it again
	 * the next time it changes: until then it was agreeing, not overriding.
	 */
	autoLogin: boolean | null
}
