// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { BattleList } from "./BattleList";
import type { Chat } from "./Chat";
import type { Logging } from "./Logging";
import type { Paths } from "./Paths";
import type { Server } from "./Server";
import type { Tweaks } from "./Tweaks";

export type Settings = { 
/**
 * Points editors at the schema next to the file.
 */
$schema: string | null, server: Server, account: Account, paths: Paths, battleList: BattleList, chat: Chat, tweaks: Tweaks, logging: Logging, };
