// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { BattleList } from "./BattleList";
import type { Chat } from "./Chat";
import type { Connection } from "./Connection";
import type { Logging } from "./Logging";
import type { Notifications } from "./Notifications";
import type { Overlay } from "./Overlay";
import type { Paths } from "./Paths";
import type { Play } from "./Play";
import type { ServerEntry } from "./ServerEntry";
import type { Tweaks } from "./Tweaks";
import type { Ui } from "./Ui";
import type { Updates } from "./Updates";

export type Settings = { 
/**
 * Points editors at the schema next to the file.
 */
$schema: string | null, 
/**
 * The lobby servers, in the order the app lists them. A fresh install
 * has BAR's.
 */
servers: Array<ServerEntry>, account: Account, connection: Connection, paths: Paths, battleList: BattleList, chat: Chat, notifications: Notifications, overlay: Overlay, play: Play, tweaks: Tweaks, logging: Logging, updates: Updates, ui: Ui, };
