// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Settings } from "./Settings";

/**
 * Serialised for the front end as `{ changed: Settings }` or `{ invalid: string }`.
 */
export type SettingsEvent = { "changed": Settings } | { "invalid": string };
