// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BattleView } from "./BattleView";
import type { ContentView } from "./ContentView";
import type { MyBattleView } from "./MyBattleView";
import type { UserView } from "./UserView";

/**
 * A room with nobody else in it.
 *
 * The same shapes the online room draws, so the front end cannot tell them
 * apart -- and a field added to `BattleView` for one has to be answered for
 * the other before this compiles, which is what keeps the two from drifting.
 *
 * It is carried whole rather than as a stream of small changes. The room is
 * one person, a handful of AIs and a map of settings; replacing it outright
 * costs little and removes every question about what a partial update means.
 */
export type SkirmishView = { battle: BattleView, my: MyBattleView, 
/**
 * The local player. The AIs are `battle.bots`, as they are online.
 */
users: Array<UserView>, me: string, content: ContentView, };
