// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a skirmish can be built from on this machine.
 */
export type SkirmishOptions = { games: Array<string>, 
/**
 * Archive file names, lowercased and underscored.
 */
maps: Array<string>, engines: Array<string>, ais: Array<string>, };
