// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of the twenty tweak slots -- `0` is the unnumbered `tweakdefs` /
 * `tweakunits` -- or the start-box override.
 */
export type Slot = { "kind": "defs", "index": number } | { "kind": "units", "index": number } | { "kind": "boxes" };
