// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BattleView } from "./BattleView";
import type { EngineStatus } from "./EngineStatus";
import type { GameRunningView } from "./GameRunningView";
import type { MyBattleView } from "./MyBattleView";
import type { Phase } from "./Phase";
import type { UserView } from "./UserView";

export type Snapshot = { phase: Phase | null, me: string | null, users: Array<UserView>, battles: Array<BattleView>, myBattle: MyBattleView | null, gameRunning: GameRunningView | null, engine: EngineStatus, };
