// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BattleView } from "./BattleView";
import type { ChannelView } from "./ChannelView";
import type { EngineStatus } from "./EngineStatus";
import type { GameRunningView } from "./GameRunningView";
import type { MyBattleView } from "./MyBattleView";
import type { Phase } from "./Phase";
import type { UserView } from "./UserView";

export type Snapshot = { phase: Phase | null, me: string | null, users: Array<UserView>, battles: Array<BattleView>, myBattle: MyBattleView | null, gameRunning: GameRunningView | null, engine: EngineStatus, 
/**
 * Channels we are in. Chat lines are not replayed — a reload keeps
 * whichever backlog the front end still holds — but membership is, so the
 * channel list is right the moment the window comes back.
 */
channels: Array<ChannelView>, };
