// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortKey } from './SortKey'

/**
 * One factor of the room order, and whether it takes part. Each runs its
 * natural way: the notable rooms first, names from A.
 */
export type SortStep = {
	by: SortKey
	/**
	 * Off, it is skipped; the list page toggles it with a click.
	 */
	on: boolean
}
