// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which modoption an arrangement came from, which is worth showing: an
 * override is somebody's deliberate choice, a set entry is the map's own.
 */
export type Source = "override" | "set";
