// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A start box in the coordinates `ADDSTARTRECT` uses: 0-200 on both axes.
 */
export type StartBox = { left: number, top: number, right: number, bottom: number, };
