// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something named at the top level: a unit key in `tweakunits`, a local,
 * an assignment or a function in `tweakdefs`.
 */
export type Symbol = { name: string, line: number, };
