// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One tag the engine reads under `weapondefs`.
 */
export type Tag = { name: string, 
/**
 * The engine's type, in plain words: `float`, `bool`, `string`, `table`...
 */
kind: string, default: string | null, description: string | null, min: string | null, max: string | null, };
