// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The box a picture is made to fill, in pixels.
 */
export type Tile = { width: number, height: number, };
