// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diagnostic } from "./Diagnostic";

/**
 * A slot's current value, ready to show.
 */
export type TweakView = { 
/**
 * The decoded Lua, exactly as stored.
 */
lua: string, 
/**
 * The same Lua through StyLua; equal to `lua` when it does not parse.
 */
formatted: string, 
/**
 * The leading `--` comment, which is how BAR names a tweak.
 */
name: string | null, 
/**
 * What Chobby's modoptions panel shows: `<length>:<hash>`.
 */
summary: string, diagnostics: Array<Diagnostic>, };
