// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Tweaks = { 
/**
 * A `stylua.toml` to format tweak Lua with; StyLua's defaults when unset.
 */
styluaConfig: string | null, 
/**
 * Slot offered when exporting a tweak, e.g. `tweakdefs1`.
 */
defaultSlot: string, };
