// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Delta } from './Delta'
import type { ServerSnapshot } from './ServerSnapshot'
import type { Snapshot } from './Snapshot'

export type UiMessage =
  | { type: 'snapshot'; data: Snapshot }
  | { type: 'session'; data: ServerSnapshot }
  | { type: 'deltas'; data: { server: string | null; deltas: Array<Delta> } }
