// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Delta } from "./Delta";
import type { Snapshot } from "./Snapshot";

export type UiMessage = { "type": "snapshot", "data": Snapshot } | { "type": "deltas", "data": Array<Delta> };
