// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far along an update is. Emitted on the `app-update` event.
 */
export type UpdateProgress = { "phase": "checking" } | { "phase": "upToDate" } | { "phase": "available", version: string, } | { "phase": "downloading", got: number, total: number, } | { "phase": "ready", version: string, } | { "phase": "failed", reason: string, };
