// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Keeping the app current.
 */
export type Updates = { 
/**
 * Whether to fetch the newest release on startup and restart into it.
 *
 * On, because an out-of-date lobby is one that quietly talks to a server
 * that has moved on, and startup is the one moment a restart costs
 * nothing. An update found while a room is joined or a game is running
 * waits in the nav for a click, whatever this says.
 */
automatic: boolean, };
