// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Keeping the app current.
 */
export type Updates = { 
/**
 * Whether to look for a newer release once a day, when the app opens.
 *
 * On, because an out-of-date lobby is one that quietly talks to a server
 * that has moved on. Looking is one small request for the release
 * manifest and nothing is downloaded or installed by itself: a newer
 * version shows in the corner of the nav, and a click on it fetches and
 * installs. Off, the corner still looks when clicked.
 */
automatic: boolean, };
