// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetUsage } from "./WidgetUsage";

/**
 * The published document.
 */
export type Usage = { generated_at: string, policy_version: string, audiences: Array<string>, windows: Array<string>, widgets: Array<WidgetUsage>, };
