// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BattleStatusView } from "./BattleStatusView";
import type { UserStatusView } from "./UserStatusView";

export type UserView = { name: string, country: string, userId: number | null, lobbyClient: string, status: UserStatusView, battleStatus: BattleStatusView | null, 
/**
 * The room the user is in.
 */
battleId: number | null, };
