// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserStatusView = { inGame: boolean, away: boolean, rank: number, moderator: boolean, bot: boolean, };
