// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A seat somebody left in the running game, drawn as their ghost.
 */
export type VacancyView = {
	name: string
	/**
	 * The room's team a teammate from the game sits on; `None` where the
	 * whole team has gone.
	 */
	allyTeam: number | null
}
