// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What this build is, for the corner of the nav.
 */
export type VersionView = { 
/**
 * The number the updater compares: `Cargo.toml`'s, via `CARGO_PKG_VERSION`.
 */
version: string, 
/**
 * The short commit hash, stamped by `build.rs`.
 */
commit: string, };
