// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What this build is, for the corner of the nav.
 */
export type VersionView = { 
/**
 * The number the updater compares: `Cargo.toml`'s, via `CARGO_PKG_VERSION`.
 */
version: string, 
/**
 * The short commit hash, stamped by `build.rs`.
 */
commit: string, 
/**
 * Whether this build may talk to the lobby server at all.
 *
 * False on macOS. Beyond All Reason publishes no Apple engine, so the
 * only one that exists is a third-party build whose author has asked
 * that it not be pointed at the community servers until they approve it
 * — and disables online play by neutering Chobby's server address
 * (`packaging/release-build.sh`, "online play is blocked outside the
 * game, not inside it"). modlobby does not read that config and speaks
 * to the server itself, so nothing about the engine stops us: honouring
 * it is this flag's job. macOS is skirmish, replays and settings.
 */
online: boolean, };
