// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What this build is, for the corner of the nav.
 */
export type VersionView = { 
/**
 * The number the updater compares: `Cargo.toml`'s, via `CARGO_PKG_VERSION`.
 */
version: string, 
/**
 * The short commit hash, stamped by `build.rs`.
 */
commit: string, 
/**
 * Whether the engine here may be run against somebody's hosted game.
 *
 * False on macOS, where the only engine that exists is a third-party
 * build its author asks not be used on the community servers. Talking in
 * a room costs those servers nothing and is left alone; playing is what
 * stops. This is the front end's copy of the answer, so it can draw a
 * room you can watch rather than one whose buttons all fail —
 * `recoil::refuse_target` is what actually enforces it.
 */
playsOnline: boolean, 
/**
 * Why no engine can be fetched onto this machine, when none can.
 *
 * `None` everywhere Beyond All Reason publishes a build. Where it does
 * not, it is `content::release::NOT_PUBLISHED_HERE` — the same fact
 * `download_engine` refuses with, carried here so the room can decline to
 * offer the download rather than offer it and be told. The engine that
 * runs there arrived by hand, so it is named rather than chosen: a picker
 * over it could only list what somebody had already put on the disk.
 *
 * The reason rather than a `bool`, so nothing can draw the refusal
 * without the words that explain it, and so the sentence is written once
 * instead of once per language.
 *
 * Not derived from `plays_online`: they are two facts with one cause
 * today, and they come apart the moment the Apple Silicon build's author
 * is approved — the servers would open while BAR's index still published
 * no Apple build, and a room deriving one from the other would go back to
 * offering a 404.
 */
noPublishedEngine: string | null, };
