// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProposalView } from "./ProposalView";

export type VoteView = { command: string, by: string | null, proposal: ProposalView, yes: number, yesNeeded: number, no: number, noNeeded: number, remainingSecs: number, };
