// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Install } from "./Install";
import type { WindowStats } from "./WindowStats";

/**
 * One widget, with its numbers per window.
 */
export type WidgetUsage = { 
/**
 * Stable key. Resolved widgets are `widget:<id>`; the rest get a key
 * derived from the name and author their own client reported.
 */
key: string, 
/**
 * Whether the reported hash was traced back to a distributable source.
 *
 * False does not mean unknown — the name, author and description below
 * come from the widget's own `GetInfo()` either way. It means we cannot
 * yet point at a file, so there is nothing to offer an install for.
 */
resolved: boolean, 
/**
 * Widget Hub id when resolved, empty otherwise.
 */
id: string, name: string, author: string, description: string, 
/**
 * Audience, then window. A document published before the split carries
 * only `all`, which is why lookups fall back to it rather than blanking.
 */
windows: { [key in string]: { [key in string]: WindowStats } }, 
/**
 * Where to get it, or why it cannot be offered. Always present: a widget
 * with no known source still says so, which is more use than a dead
 * button.
 */
install: Install, 
/**
 * A picture of the widget, empty when none is known. Hub covers and
 * repository pictures are their own hosts' URLs; Discord screenshots are
 * served by pve.bar, for widgets whose licence lets it. Never fetched by
 * the webview directly — see `thumbs.rs`.
 */
image: string, };
