// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a widget's presence in the config looks like.
 */
export type WidgetState = {
	/**
	 * `GetInfo().name`, the same key the replay telemetry reports.
	 */
	name: string
	/**
	 * Load order. Zero means the player switched it off.
	 */
	order: bigint
	/**
	 * Whether the widget has saved settings in `data`.
	 */
	has_settings: boolean
}
