// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledWidget } from './InstalledWidget'
import type { LocalWidget } from './LocalWidget'
import type { WidgetState } from './WidgetState'

/**
 * What modlobby has installed, and what BAR's own config says about it.
 *
 * Two different questions, deliberately kept apart. The ledger says what
 * *modlobby* put on disk, and is what delete is allowed to act on. The config
 * says what *BAR* knows about, whoever installed it — so a widget the player
 * added by hand can still be switched off from here, and one modlobby
 * installed can still be missing from the config until the game has loaded it
 * once.
 */
export type WidgetStatus = {
	/**
	 * Usage keys modlobby installed, with what it wrote.
	 */
	installed: Array<InstalledWidget>
	/**
	 * Every widget named in `BYAR.lua`, ours or not.
	 */
	configured: Array<WidgetState>
	/**
	 * Whether a game is running, which is when config edits are refused.
	 */
	locked: boolean
	/**
	 * Where installs land, so the interface can say it rather than imply it.
	 */
	writeDir: string
	/**
	 * Every widget file BAR would load, whoever put it there.
	 */
	local: Array<LocalWidget>
}
