// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowStats } from "./WindowStats";

/**
 * One widget, with its numbers per window.
 */
export type WidgetUsage = { 
/**
 * Stable key. Resolved widgets are `widget:<id>`; the rest get a key
 * derived from the name and author their own client reported.
 */
key: string, 
/**
 * Whether the reported hash was traced back to a distributable source.
 *
 * False does not mean unknown — the name, author and description below
 * come from the widget's own `GetInfo()` either way. It means we cannot
 * yet point at a file, so there is nothing to offer an install for.
 */
resolved: boolean, 
/**
 * Widget Hub id when resolved, empty otherwise.
 */
id: string, name: string, author: string, description: string, windows: { [key in string]: WindowStats }, };
