// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a widget did over one window.
 */
export type WindowStats = { 
/**
 * Position within this window, 1 is most used.
 */
rank: number, 
/**
 * Distinct players who reported it at all.
 */
players: number, 
/**
 * Distinct players who had it *enabled* at least once.
 */
players_active: number, 
/**
 * `players_active / players`: install-and-keep rate. A widget people
 * install and then switch off scores low here and nowhere else.
 */
retention: number, sightings: number, replays: number, 
/**
 * Days in this window that have actually been harvested.
 */
days_covered: number, 
/**
 * `days_covered` over the window length. Below 1.0 the window is a
 * partial view — the pipeline backfills history a slice at a time, so a
 * year window can legitimately hold a fortnight early on.
 */
coverage: number, };
