-- Widget Custom data and order, order = 0 disabled widget
return {
	allowUserWidgets = true,
	data = {
		AdvPlayersList = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["API Builder Queue"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["API LOS Combiner GL4"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Attack AoE"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Grid Menu"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Pause On Ally Damage"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Raptor Grid Draw"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Unit Stats"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Map Edge Extension"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 000"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 003"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 006"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 009"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 012"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 015"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 018"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 021"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 024"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 027"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 030"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 033"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 036"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 039"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 042"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 045"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 048"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 051"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 054"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 057"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 060"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 063"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 066"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 069"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 072"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 075"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 078"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 081"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 084"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 087"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 090"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 093"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 096"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 099"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 102"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 105"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 108"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 111"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 114"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 117"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 120"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 123"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 126"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 129"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 132"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 135"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 138"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 141"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 144"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 147"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 150"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 153"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 156"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 159"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 162"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 165"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 168"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 171"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 174"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 177"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 180"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 183"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 186"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 189"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 192"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 195"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
		["Filler Widget 198"] = {
			customScale = 1,
			enabled = true,
			format = "hp {cur}/{max} }",
			label = 'a } and a { in single quotes',
			nested = {
				depth = 2,
				["awkward key = with equals"] = 3,
				inner = { deeper = true },
			},
			widgetPosX = 5.34322071,
		},
	},
	order = {
		["API Builder Queue"] = 69,
		["API LOS Combiner GL4"] = 0,
		AdvPlayersList = 51,
		["Area Command Filter"] = 12345,
		["Attack AoE"] = 61,
		["Auto Cloak Units"] = 26,
		["Commander Name Tags"] = 12,
		["Filler Widget 000"] = 0,
		["Filler Widget 001"] = 7,
		["Filler Widget 002"] = 14,
		["Filler Widget 003"] = 21,
		["Filler Widget 004"] = 28,
		["Filler Widget 005"] = 35,
		["Filler Widget 006"] = 42,
		["Filler Widget 007"] = 49,
		["Filler Widget 008"] = 56,
		["Filler Widget 009"] = 63,
		["Filler Widget 010"] = 70,
		["Filler Widget 011"] = 77,
		["Filler Widget 012"] = 84,
		["Filler Widget 013"] = 91,
		["Filler Widget 014"] = 98,
		["Filler Widget 015"] = 105,
		["Filler Widget 016"] = 112,
		["Filler Widget 017"] = 119,
		["Filler Widget 018"] = 126,
		["Filler Widget 019"] = 133,
		["Filler Widget 020"] = 140,
		["Filler Widget 021"] = 147,
		["Filler Widget 022"] = 154,
		["Filler Widget 023"] = 161,
		["Filler Widget 024"] = 168,
		["Filler Widget 025"] = 175,
		["Filler Widget 026"] = 182,
		["Filler Widget 027"] = 189,
		["Filler Widget 028"] = 196,
		["Filler Widget 029"] = 203,
		["Filler Widget 030"] = 210,
		["Filler Widget 031"] = 217,
		["Filler Widget 032"] = 224,
		["Filler Widget 033"] = 231,
		["Filler Widget 034"] = 238,
		["Filler Widget 035"] = 245,
		["Filler Widget 036"] = 252,
		["Filler Widget 037"] = 259,
		["Filler Widget 038"] = 266,
		["Filler Widget 039"] = 273,
		["Filler Widget 040"] = 280,
		["Filler Widget 041"] = 287,
		["Filler Widget 042"] = 294,
		["Filler Widget 043"] = 1,
		["Filler Widget 044"] = 8,
		["Filler Widget 045"] = 15,
		["Filler Widget 046"] = 22,
		["Filler Widget 047"] = 29,
		["Filler Widget 048"] = 36,
		["Filler Widget 049"] = 43,
		["Filler Widget 050"] = 50,
		["Filler Widget 051"] = 57,
		["Filler Widget 052"] = 64,
		["Filler Widget 053"] = 71,
		["Filler Widget 054"] = 78,
		["Filler Widget 055"] = 85,
		["Filler Widget 056"] = 92,
		["Filler Widget 057"] = 99,
		["Filler Widget 058"] = 106,
		["Filler Widget 059"] = 113,
		["Filler Widget 060"] = 120,
		["Filler Widget 061"] = 127,
		["Filler Widget 062"] = 134,
		["Filler Widget 063"] = 141,
		["Filler Widget 064"] = 148,
		["Filler Widget 065"] = 155,
		["Filler Widget 066"] = 162,
		["Filler Widget 067"] = 169,
		["Filler Widget 068"] = 176,
		["Filler Widget 069"] = 183,
		["Filler Widget 070"] = 190,
		["Filler Widget 071"] = 197,
		["Filler Widget 072"] = 204,
		["Filler Widget 073"] = 211,
		["Filler Widget 074"] = 218,
		["Filler Widget 075"] = 225,
		["Filler Widget 076"] = 232,
		["Filler Widget 077"] = 239,
		["Filler Widget 078"] = 246,
		["Filler Widget 079"] = 253,
		["Filler Widget 080"] = 260,
		["Filler Widget 081"] = 267,
		["Filler Widget 082"] = 274,
		["Filler Widget 083"] = 281,
		["Filler Widget 084"] = 288,
		["Filler Widget 085"] = 295,
		["Filler Widget 086"] = 2,
		["Filler Widget 087"] = 9,
		["Filler Widget 088"] = 16,
		["Filler Widget 089"] = 23,
		["Filler Widget 090"] = 30,
		["Filler Widget 091"] = 37,
		["Filler Widget 092"] = 44,
		["Filler Widget 093"] = 51,
		["Filler Widget 094"] = 58,
		["Filler Widget 095"] = 65,
		["Filler Widget 096"] = 72,
		["Filler Widget 097"] = 79,
		["Filler Widget 098"] = 86,
		["Filler Widget 099"] = 93,
		["Filler Widget 100"] = 100,
		["Filler Widget 101"] = 107,
		["Filler Widget 102"] = 114,
		["Filler Widget 103"] = 121,
		["Filler Widget 104"] = 128,
		["Filler Widget 105"] = 135,
		["Filler Widget 106"] = 142,
		["Filler Widget 107"] = 149,
		["Filler Widget 108"] = 156,
		["Filler Widget 109"] = 163,
		["Filler Widget 110"] = 170,
		["Filler Widget 111"] = 177,
		["Filler Widget 112"] = 184,
		["Filler Widget 113"] = 191,
		["Filler Widget 114"] = 198,
		["Filler Widget 115"] = 205,
		["Filler Widget 116"] = 212,
		["Filler Widget 117"] = 219,
		["Filler Widget 118"] = 226,
		["Filler Widget 119"] = 233,
		["Filler Widget 120"] = 240,
		["Filler Widget 121"] = 247,
		["Filler Widget 122"] = 254,
		["Filler Widget 123"] = 261,
		["Filler Widget 124"] = 268,
		["Filler Widget 125"] = 275,
		["Filler Widget 126"] = 282,
		["Filler Widget 127"] = 289,
		["Filler Widget 128"] = 296,
		["Filler Widget 129"] = 3,
		["Filler Widget 130"] = 10,
		["Filler Widget 131"] = 17,
		["Filler Widget 132"] = 24,
		["Filler Widget 133"] = 31,
		["Filler Widget 134"] = 38,
		["Filler Widget 135"] = 45,
		["Filler Widget 136"] = 52,
		["Filler Widget 137"] = 59,
		["Filler Widget 138"] = 66,
		["Filler Widget 139"] = 73,
		["Filler Widget 140"] = 80,
		["Filler Widget 141"] = 87,
		["Filler Widget 142"] = 94,
		["Filler Widget 143"] = 101,
		["Filler Widget 144"] = 108,
		["Filler Widget 145"] = 115,
		["Filler Widget 146"] = 122,
		["Filler Widget 147"] = 129,
		["Filler Widget 148"] = 136,
		["Filler Widget 149"] = 143,
		["Filler Widget 150"] = 150,
		["Filler Widget 151"] = 157,
		["Filler Widget 152"] = 164,
		["Filler Widget 153"] = 171,
		["Filler Widget 154"] = 178,
		["Filler Widget 155"] = 185,
		["Filler Widget 156"] = 192,
		["Filler Widget 157"] = 199,
		["Filler Widget 158"] = 206,
		["Filler Widget 159"] = 213,
		["Filler Widget 160"] = 220,
		["Filler Widget 161"] = 227,
		["Filler Widget 162"] = 234,
		["Filler Widget 163"] = 241,
		["Filler Widget 164"] = 248,
		["Filler Widget 165"] = 255,
		["Filler Widget 166"] = 262,
		["Filler Widget 167"] = 269,
		["Filler Widget 168"] = 276,
		["Filler Widget 169"] = 283,
		["Filler Widget 170"] = 290,
		["Filler Widget 171"] = 297,
		["Filler Widget 172"] = 4,
		["Filler Widget 173"] = 11,
		["Filler Widget 174"] = 18,
		["Filler Widget 175"] = 25,
		["Filler Widget 176"] = 32,
		["Filler Widget 177"] = 39,
		["Filler Widget 178"] = 46,
		["Filler Widget 179"] = 53,
		["Filler Widget 180"] = 60,
		["Filler Widget 181"] = 67,
		["Filler Widget 182"] = 74,
		["Filler Widget 183"] = 81,
		["Filler Widget 184"] = 88,
		["Filler Widget 185"] = 95,
		["Filler Widget 186"] = 102,
		["Filler Widget 187"] = 109,
		["Filler Widget 188"] = 116,
		["Filler Widget 189"] = 123,
		["Filler Widget 190"] = 130,
		["Filler Widget 191"] = 137,
		["Filler Widget 192"] = 144,
		["Filler Widget 193"] = 151,
		["Filler Widget 194"] = 158,
		["Filler Widget 195"] = 165,
		["Filler Widget 196"] = 172,
		["Filler Widget 197"] = 179,
		["Filler Widget 198"] = 186,
		["Filler Widget 199"] = 193,
		["Grid Menu"] = 7,
		["Map Edge Extension"] = 88,
		["Pause On Ally Damage"] = 0,
		["Ping Wheel"] = 44,
		["Raptor Grid Draw"] = 91,
		["Smart Nanos"] = 0,
		["Unit Stats"] = 33,
		["Widget Selector"] = 1,
	},
}
